services:
  rgrokd:
    image: "ghcr.io/EdwardJXLi/rgrokd:latest"
    restart: always
    volumes:
      - "./rgrokd:/var/opt/rgrokd"
    ports:
      - "3320:3320"
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: rgrokd
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

volumes:
  pg_data:
