version: '3'

vars:
  BUILD_VERSION:
    sh: echo ${BUILD_VERSION}
  BUILD_COMMIT:
    sh: git rev-parse HEAD
  BUILD_DATE:
    sh: date -u '+%Y-%m-%d %I:%M:%S %Z'

tasks:
  rgrokd:
    desc: Build the binary and start the rgrokd
    deps: [build-rgrokd]
    cmds:
      - ./.bin/rgrokd
  build:
    deps: [build-rgrok, build-rgrokd]
  build-rgrok:
    desc: Build the binary of rgrok
    cmds:
      - go build -v -trimpath -o ./.bin/rgrok ./rgrok/cli
  build-rgrokd:
    desc: Build the binary of rgrokd
    cmds:
      - go build -v -trimpath -o ./.bin/rgrokd ./rgrokd/cli
    sources:
      - go.mod
      - rgrokd/cli/*.go
      - internal/**/*
    method: timestamp
  build-rgrokd-web:
    desc: Build the web app of rgrokd
    cmds:
      - pnpm --dir rgrokd/web run build

  build-rgrokd-release:
    desc: Build the release binary of rgrokd
    cmds:
      - go build -v
        -ldflags '
        -X "main.version={{.BUILD_VERSION}}"
        -X "main.commit={{.BUILD_COMMIT}}"
        -X "main.date={{.BUILD_DATE}}"'
        -trimpath
        -o ./.bin/rgrokd
        ./rgrokd/cli
